---
name: Changeme
description: |
  To change this file, modify settings.yaml, then run `make all`
license: 
  type: MIT # MIT, GPL
  owner: Spencer Owen
  year: 2020
CAD: 
  - cube
resources:
  foo: https://example.com
# photos:
#   - photos/IMG_0987.jpeg
# fusion_link: herpderp
links:
  # Thingiverse: https://www.thingiverse.com/thing:xxxx
  # Prusa: https://foo.com
  # GrabCad: https://foo.com
